###############################################
#
# Consignor Name clean up
#
#
#
#
#
###############################################

wrangle_consignor_names <- function (innames)
  
{

library(stringr)

outnames <-  innames
# parse names to get a coherent list taking into a/c sp mistakes etc
#outnames <-  str_replace_all( outnames, "[[:punct:]]", "")
outnames <-  str_replace_all( outnames, "[^[:alnum:][:space:]]", "")
outnames <-  str_replace_all( outnames, "From ", "")
outnames <-  str_replace_all( outnames, " Ireland", "")
outnames <-  str_replace_all( outnames, " Agent", "")
outnames <-  str_replace_all( outnames, "Ireland", "")
outnames <-  str_replace_all( outnames, "Agent", "")
outnames <-  str_replace_all( outnames, " agent", "")
outnames <-  str_replace_all( outnames, "agent", "")
outnames <-  str_replace_all( outnames, "Stables ", "Stables")
outnames <-  str_replace_all( outnames, "M Bastard", "Malcolm Bastard")
outnames <-  str_replace_all( outnames, "Bastard Malcolm", "Malcolm Bastard")
outnames <-  str_replace_all( outnames, "Leahy Brian", "Brian Leahy")
outnames <-  str_replace_all( outnames, "Leahy B", "Brian Leahy")
outnames <-  str_replace_all( outnames, "Brian Leahy", "Leahy Brian")
outnames <-  str_replace_all( outnames, "Mr Bal Sohal from ", "")
outnames <-  str_replace_all( outnames, " Co Tipperary", "")
outnames <-  str_replace_all( outnames, " StablesCo Tipperary", " Stables")
outnames <-  str_replace_all( outnames, "A Gentleman from ", "")
outnames <-  str_replace_all( outnames, "a Gentleman from ", "")
outnames <-  str_replace_all( outnames, "A Partnership from ", "")
outnames <-  str_replace_all( outnames, "a Partnership from", "")
outnames <-  str_replace_all( outnames, " Ball", "Ball")
outnames <-  str_replace_all( outnames, " Brook", "Brook")
outnames <-  str_replace_all( outnames, " Mock", "Mock")
outnames <-  str_replace_all( outnames, " Jamie", "Jamie")
outnames <-  str_replace_all( outnames, " The", "The")

outnames <-  str_replace_all( outnames, " Knock", "Knock")
outnames <-  str_replace_all( outnames, " Herring", "Herring")
outnames <-  str_replace_all( outnames, " Meadow", "Meadow")
outnames <-  str_replace_all( outnames, " Church", "Church")
outnames <-  str_replace_all( outnames, " Rectory", "Rectory")
outnames <-  str_replace_all( outnames, " Hare", "Hare")
outnames <-  str_replace_all( outnames, "Tally Ho ", "TallyHo ")
outnames <-  str_replace_all( outnames, " in ", " In ")
outnames <-  str_replace_all( outnames, " LLC", "")
outnames <-  str_replace_all( outnames, "Ballycrighaun Stables", "Ballycrighaun Stud")
outnames <-  str_replace_all( outnames, "  Mr Peter Wheatley from Ermyn Lodge Stud", "")
outnames <-  str_replace_all( outnames, " from Ermyn Lodge Stud", "")
outnames <-  str_replace_all( outnames, "Hartley De", "HartleyDe")
outnames <-  str_replace_all( outnames, "StablesR Charlton", "Stables")
outnames <-  str_replace_all( outnames, "Mocklershill Stables", "Mocklershill")
outnames <-  str_replace_all( outnames, "Bloodstock from Kingwood Stud", "Stud")
outnames <-  str_replace_all( outnames, "Partnership III from Kingwood Stud", "Stud")
outnames <-  str_replace_all( outnames, " Inc", "")
outnames <-  str_replace_all( outnames, "The Ras", "The RAS")
outnames <-  str_replace_all( outnames, " Mew Stables", " Mew Stable")
outnames <-  str_replace_all( outnames, " Mew Stable", " Mew Stables")
outnames <-  str_replace_all( outnames, " LLC", "")
outnames <-  str_replace_all( outnames, " Ltd", "")
outnames <-  str_replace_all( outnames, " Ltd.", "")
outnames <-  str_replace_all( outnames, " agemt", "")
outnames <-  str_replace_all( outnames, "Ballyhane Sales", "Ballyhane")
outnames <-  str_replace_all( outnames, "Blythe Park Stud from ", "")
outnames <-  str_replace_all( outnames, "Oaks Farm", "Oak Farm")
outnames <-  str_replace_all( outnames, "Castlefarm", "Castle Farm")
outnames <-  str_replace_all( outnames, "Churchview", "Church View")
outnames <-  str_replace_all( outnames, "Churchview ", "Church View ")
outnames <-  str_replace_all( outnames, "Church Farm Stables Bloodstock fromChurch", "Church")
outnames <-  str_replace_all( outnames, "Church Farm Stables", "Church Farm")
outnames <-  str_replace_all( outnames, "Church Farm Stable", "Church Farm")
outnames <-  str_replace_all( outnames, "Church Farm", "Church Farm Stables")
outnames <-  str_replace_all( outnames, "Clenagh Castle Stud", "Clenagh Castle")
outnames <-  str_replace_all( outnames, "Clenagh Castle", "Clenagh Castle Stud")
outnames <-  str_replace_all( outnames, "Channel Consignment", "Jamie Railton")
outnames <-  str_replace_all( outnames, "Railton", "Jamie Railton")
outnames <-  str_replace_all( outnames, "Jamie Railton Railton", "Jamie Railton")
outnames <-  str_replace_all( outnames, "J Railton", "Jamie Railton")
outnames <-  str_replace_all( outnames, " Sales Agency", "")
outnames <-  str_replace_all( outnames, "Hoby  ", "Hoby and ")
outnames <-  str_replace_all( outnames, "Hoby Knight", "Hoby and Layna Knight")
outnames <-  str_replace_all( outnames, "Hoby Kight", "Hoby and Layna Knight")
outnames <-  str_replace_all( outnames, "Derrymore House Stables", "Derrymore House")
outnames <-  str_replace_all( outnames, "Derrymore House", "Derrymore House Stables")
outnames <-  str_replace_all( outnames, "Bramblestown Stables", "Bramblestown")
outnames <-  str_replace_all( outnames, "Bramblestown", "Bramblestown Stables")
outnames <-  str_replace_all( outnames, "K Walsh", "Katie Walsh")
outnames <-  str_replace_all( outnames, "Katie Walsh ", "Katie Walsh")
outnames <-  str_replace_all( outnames, " from Bushy Park Stables", "")
outnames <-  str_replace_all( outnames, " StablesUSA", " Stables")
outnames <-  str_replace_all( outnames, " StablesInc", " Stables")
outnames <-  str_replace_all( outnames, "Knockanglass Stables", "Knockanglass Stable")
outnames <-  str_replace_all( outnames, "Knockanglass Stable", "Knockanglass")
outnames <-  str_replace_all( outnames, "Knockanglass", "Knockanglass Stables")
outnames <-  str_replace_all( outnames, " from Seven Springs Stables", "")
outnames <-  str_replace_all( outnames, "Crampscastle Bloodstock from Crampscastle Stables", "Crampcastle Bloodstock")
outnames <-  str_replace_all( outnames, "Crown Select from ", "")
outnames <-  str_replace_all( outnames, "Mick Murphy  Susan Finn fromBallinahulla", "Ballinahulla Stables")
outnames <-  str_replace_all( outnames, "Susan Finn  Fergus Foley fromBallinahulla", "Ballinahulla Stables")

outnames <-  str_replace_all( outnames, "Ballinahulla Stables Stables", "Ballinahulla Stables")

outnames <-  str_replace_all( outnames, "StablesJ Osborne", "Stables")
outnames <-  str_replace_all( outnames, "Southill Stud from ", "")
outnames <-  str_replace_all( outnames, "Diane Williams from ", "")
outnames <-  str_replace_all( outnames, "Shadwell Estate Company from ", "")
outnames <-  str_replace_all( outnames, "Sherbourne Lodge Stud", "Sherbourne Lodge")
outnames <-  str_replace_all( outnames, "Sherbourne Lodge Stables", "Sherbourne Lodge")
outnames <-  str_replace_all( outnames, "S  J Campbell from ", "")
outnames <-  str_replace_all( outnames, "Sportsdays from ", "")
outnames <-  str_replace_all( outnames, "The RAS Partnership from ", "")
outnames <-  str_replace_all( outnames, "Daars North Stud from ", "")
outnames <-  str_replace_all( outnames, "Countrywide Classics from ", "")
outnames <-  str_replace_all( outnames, "Centaur Bloodstock Agency from ", "")
outnames <-  str_replace_all( outnames, "Coleman Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Daisyhill Farm", "Daisyhill Stables")
outnames <-  str_replace_all( outnames, "StablesJ Hills", "Stables")
outnames <-  str_replace_all( outnames, "Georgestown Stud fromKnockgraffon ", "Knockgraffon ")
outnames <-  str_replace_all( outnames, "Killcorral House Stables", "Kilcorral House")
outnames <-  str_replace_all( outnames, "Knockatrina House Stud", "Knockatrina House")
outnames <-  str_replace_all( outnames, "Miss ", "")
outnames <-  str_replace_all( outnames, "Redland Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Tullamaine Castle Stud and Partners fromMeadowview ", "Meadowview ")
outnames <-  str_replace_all( outnames, "Rathmuck Stud", "Rathmuck Stables")
outnames <-  str_replace_all( outnames, "StablesN Tinkler", "Stables")
outnames <-  str_replace_all( outnames, "Rathmuck Stud", "Rathmuck Stables")
outnames <-  str_replace_all( outnames, "Mr ", "")
outnames <-  str_replace_all( outnames, "Moubarar Racing from ", "")
outnames <-  str_replace_all( outnames, "Moubarak Racing from ", "")
outnames <-  str_replace_all( outnames, "Noel Rothwell from ", "")
outnames <-  str_replace_all( outnames, "Church Farm Stables Bloodstock fromChurch ", "Church ")
outnames <-  str_replace_all( outnames, "Huggan Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Highbank Stud from ", "")
outnames <-  str_replace_all( outnames, "Tony Kilduff from ", "")
outnames <-  str_replace_all( outnames, "Richard Heaney fromBallyknock ", "Ballyknock ")
outnames <-  str_replace_all( outnames, "Eastwind Racing  Martha Trussel fromThe Old Manor", "The Old Manor Stables")
outnames <-  str_replace_all( outnames, "Knockgraffon Stud", "Knockgraffon Stables")
outnames <-  str_replace_all( outnames, "Meadowview", "Meadow View")
outnames <-  str_replace_all( outnames, "Kilcorral House Stables", "Kilcorral House")
outnames <-  str_replace_all( outnames, "Niall", "Nial")
outnames <-  str_replace_all( outnames, "Richard Nevin fromBallintemple", "Ballintemple")
outnames <-  str_replace_all( outnames, "Roger Marley fromChurch", "Church")
outnames <-  str_replace_all( outnames, " Seven", "Seven")
outnames <-  str_replace_all( outnames, " Oak Farm", "Oak Farm")
outnames <-  str_replace_all( outnames, "Azpura", "Azpurua")
outnames <-  str_replace_all( outnames, "Azpurua Stables", "Azpurua Stable")
outnames <-  str_replace_all( outnames, "Ballinahulla Stud", "Ballinahulla Stables")
outnames <-  str_replace_all( outnames, "Fergus Foley fromBallinahulla", "Ballinahulla")
outnames <-  str_replace_all( outnames, "Philip Brady fromMocklershill", "Mocklershill")
outnames <-  str_replace_all( outnames, "Gaybrook Lodge Stud", "Gaybrook Lodge")
outnames <-  str_replace_all( outnames, "Gaybrook Lodge ", "Gaybrook Lodge")
outnames <-  str_replace_all( outnames, "Ballyhane Stud", "Ballyhane")
outnames <-  str_replace_all( outnames, "Ballyhane", "Ballyhane Stud")
outnames <-  str_replace_all( outnames, "De Meric", "de Meric")
outnames <-  str_replace_all( outnames, "Stablesagemt", "Stables")
outnames <-  str_replace_all( outnames, "OffThe", "Off The")
outnames <-  str_replace_all( outnames, "Rathvin Stables", "Rathvin Stud")
outnames <-  str_replace_all( outnames, "Hammock Farm", "Hammock")
outnames <-  str_replace_all( outnames, "Harefield Lodge Stud", "Harefield Lodge")
outnames <-  str_replace_all( outnames, "Harefield Lodge Stables", "Harefield Lodge")
outnames <-  str_replace_all( outnames, "Harefield Stud", "Harefield Lodge")
outnames <-  str_replace_all( outnames, "Longways", "Longway")
outnames <-  str_replace_all( outnames, " France", "")
outnames <-  str_replace_all( outnames, "Egmont Stud from ", "")
outnames <-  str_replace_all( outnames, "Friarstown Bloodstock", "Friarstown Stud")
outnames <-  str_replace_all( outnames, "J McMahon fromThe", "The")
outnames <-  str_replace_all( outnames, "Juddmonte Farms from ", "")
outnames <-  str_replace_all( outnames, "Little Wood", "Littlewood")
outnames <-  str_replace_all( outnames, "Milltown Stables", "Milltown Stud")
outnames <-  str_replace_all( outnames, "Ms ", "")
outnames <-  str_replace_all( outnames, "R Nevin fromBallintemple", "Ballintemple")
outnames <-  str_replace_all( outnames, "Susan Finn fromBallinahulla", "Ballinahulla")
outnames <-  str_replace_all( outnames, "To dissolve a", "To Dissolve A")
outnames <-  str_replace_all( outnames, "To Dissolve a", "To Dissolve A")
outnames <-  str_replace_all( outnames, "P Henley from ", "")
outnames <-  str_replace_all( outnames, "J Kent from ", "")
outnames <-  str_replace_all( outnames, "Sir Eric Parker from ", "")
outnames <-  str_replace_all( outnames, "Sparsholt Stud from ", "")
outnames <-  str_replace_all( outnames, "T J Pole from ", "")
outnames <-  str_replace_all( outnames, "Phoenix Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Messrs Darley  Townsend from ", "")
outnames <-  str_replace_all( outnames, "Martin Francis from ", "")
outnames <-  str_replace_all( outnames, "Mairead Lawlor from ", "")
outnames <-  str_replace_all( outnames, "M Woodcock from ", "")
outnames <-  str_replace_all( outnames, "Jamie Railton Bloodstock", "Jamie Railton")
outnames <-  str_replace_all( outnames, "Herbertstown House Stud", "Herbertstown House Stables")
outnames <-  str_replace_all( outnames, "Home Farm Stud", "Home Farm")
outnames <-  str_replace_all( outnames, "Home Farm", "Home Farm Stud")
outnames <-  str_replace_all( outnames, "Hilary McLoughlin from ", "")
outnames <-  str_replace_all( outnames, "Ann Casey fromBallinscala", "Ballinscala")
outnames <-  str_replace_all( outnames, "Aileen Sloan Lee fromBallyduff", "Ballyduff")
outnames <-  str_replace_all( outnames, "WB Mactaggart from ", "")
outnames <-  str_replace_all( outnames, "Unicorn Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Willie Maher from ", "")
outnames <-  str_replace_all( outnames, "Tina Kearney from ", "")
outnames <-  str_replace_all( outnames, "Snowdrop Stud Co from ", "")
outnames <-  str_replace_all( outnames, "Showtime Ice Cream from ", "")
outnames <-  str_replace_all( outnames, "Richard Brabazon from ", "")
outnames <-  str_replace_all( outnames, "Patrick Verling from ", "")
outnames <-  str_replace_all( outnames, "Mrs J E Young from ", "")
outnames <-  str_replace_all( outnames, "Mrs Margaret Fallon from ", "")
outnames <-  str_replace_all( outnames, "Mrs Pamela Brandon from ", "")
outnames <-  str_replace_all( outnames, "Mark Pitman Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "M Moriarty from ", "")
outnames <-  str_replace_all( outnames, "John Quinn from ", "")
outnames <-  str_replace_all( outnames, "J Doyle from ", "")
outnames <-  str_replace_all( outnames, "Gordon Li from ", "")
outnames <-  str_replace_all( outnames, "G  D Haine Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Ford Enterprises from ", "")
outnames <-  str_replace_all( outnames, "Fehily Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Equiname fromThe", "The")
outnames <-  str_replace_all( outnames, "Declan Johnson from ", "")
outnames <-  str_replace_all( outnames, "Declan Coyne from ", "")
outnames <-  str_replace_all( outnames, "Colm White from ", "")
outnames <-  str_replace_all( outnames, "W Goddard from ", "")
outnames <-  str_replace_all( outnames, "Tracey Eaton from ", "")
outnames <-  str_replace_all( outnames, "StablesLtd", "Stables")
outnames <-  str_replace_all( outnames, "S Doyle from ", "")
outnames <-  str_replace_all( outnames, "Ron Hull from ", "")
outnames <-  str_replace_all( outnames, "Pierre Julienne from ", "")
outnames <-  str_replace_all( outnames, "Nightingale Stud from ", "")
outnames <-  str_replace_all( outnames, "Messrs J  S Fallon from ", "")
outnames <-  str_replace_all( outnames, "Messrs Barry  Donal Conroy from ", "")
outnames <-  str_replace_all( outnames, "Michael Burke from ", "")
outnames <-  str_replace_all( outnames, "Knocknasna Stud from ", "")
outnames <-  str_replace_all( outnames, "John OByrne fromThe", "The")
outnames <-  str_replace_all( outnames, "J  S Fallon from ", "")
outnames <-  str_replace_all( outnames, "John Murray from ", "")
outnames <-  str_replace_all( outnames, "Justin Rea from ", "")
outnames <-  str_replace_all( outnames, "R Prowse from ", "")
outnames <-  str_replace_all( outnames, "P Grainger from ", "")
outnames <-  str_replace_all( outnames, "Paul Kiernan from ", "")
outnames <-  str_replace_all( outnames, "Lisa English from ", "")
outnames <-  str_replace_all( outnames, "Limestone Stud from ", "")
outnames <-  str_replace_all( outnames, "Joan Brennan from ", "")
outnames <-  str_replace_all( outnames, "Jim Doyle from ", "")
outnames <-  str_replace_all( outnames, "Westfields Stables", "Westfield Stables")
outnames <-  str_replace_all( outnames, "Suir View Stables", "Suirview Stables")
outnames <-  str_replace_all( outnames, "Sarah Dent  Clair Turner from ", "")
outnames <-  str_replace_all( outnames, "Padraic Connolly from ", "")
outnames <-  str_replace_all( outnames, "Mrs C C RegaladoGonzales from ", "")
outnames <-  str_replace_all( outnames, "Mrs A M Upsdell fromThe", "The")
outnames <-  str_replace_all( outnames, "Mayden Stud from ", "")
outnames <-  str_replace_all( outnames, "Lisa English from ", "")
outnames <-  str_replace_all( outnames, "Limestone Stud from ", "")
outnames <-  str_replace_all( outnames, "I Muir from ", "")
outnames <-  str_replace_all( outnames, "Brighton Farm from ", "")
outnames <-  str_replace_all( outnames, "A Kennedy fromRectory", "Rectory")
outnames <-  str_replace_all( outnames, "A B Phipps fromChurch", "Church")
outnames <-  str_replace_all( outnames, "A D Plumb  C Drew from ", "")
outnames <-  str_replace_all( outnames, "Adrian OShea from ", "")
outnames <-  str_replace_all( outnames, "E Rawlings from ", "")
outnames <-  str_replace_all( outnames, "D OGorman from ", "")
outnames <-  str_replace_all( outnames, "Ash Tree Farm Stud", "Ash Tree Farm")
outnames <-  str_replace_all( outnames, "A Ross from ", "")
outnames <-  str_replace_all( outnames, "Ermyn Lodge Stud", "Ermyn Lodge")
outnames <-  str_replace_all( outnames, "Elm Tree Farm Stud", "Elm Tree Stud")
outnames <-  str_replace_all( outnames, " Athnid Stables", "Athnid Stables")
outnames <-  str_replace_all( outnames, " Georgia House Stud", "Georgia House Stud")
outnames <-  str_replace_all( outnames, " Questus 7", "Questus 7")
outnames <-  str_replace_all( outnames, "Athnid StablesM Quinlan", "Athnid Stables")
outnames <-  str_replace_all( outnames, " Rosewood Stud", "Rosewood Stud")
outnames <-  str_replace_all( outnames, " Furnace Mill Stud", "Furnace Mill Stud")
outnames <-  str_replace_all( outnames, " Hazelwood Stables", "Hazlewood Stables")
outnames <-  str_replace_all( outnames, "Abbey Leix Stud Farm", "Abbeyleix Stud")
outnames <-  str_replace_all( outnames, "Ballinvana House Stables", "Ballinvana House Stud")
outnames <-  str_replace_all( outnames, "C Parkhouse from Culm Springs", "Culm springs")
outnames <-  str_replace_all( outnames, "DJ Guerin from", "")
outnames <-  str_replace_all( outnames, "Danny ODonovan from ", "")
outnames <-  str_replace_all( outnames, "Friends Stud from ", "")
outnames <-  str_replace_all( outnames, "Gladstone Bloodstock from", "")
outnames <-  str_replace_all( outnames, "Grangecon Stud from ", "")
outnames <-  str_replace_all( outnames, "Grange Clare", "Grangeclare")
outnames <-  str_replace_all( outnames, "Jaykayenn Syndicate from ", "")
outnames <-  str_replace_all( outnames, "John Linehan from ", "")
outnames <-  str_replace_all( outnames, "Messrs ", "")
outnames <-  str_replace_all( outnames, "Moyns Park Estate Stud from ", "")
outnames <-  str_replace_all( outnames, "Mrs R D Peacock from ", "")
outnames <-  str_replace_all( outnames, "Mrs S Kennedy from ", "")
outnames <-  str_replace_all( outnames, "Nigel Spreadbury from ", "")
outnames <-  str_replace_all( outnames, "On behalf ofThe", "The")
outnames <-  str_replace_all( outnames, "Patrick Casey from ", "")
outnames <-  str_replace_all( outnames, "Penny Farm from ", "")
outnames <-  str_replace_all( outnames, "Shadwell Estate Co from ", "")
outnames <-  str_replace_all( outnames, "StablesJ Noseda", "Stables")
outnames <-  str_replace_all( outnames, "Susan A Finn fromBallinahulla", "Ballinahulla")
outnames <-  str_replace_all( outnames, "D Harvey from ", "")
outnames <-  str_replace_all( outnames, "D  Mrs M Dean from ", "")
outnames <-  str_replace_all( outnames, "D Harding from ", "")
outnames <-  str_replace_all( outnames, "Dell Farm from ", "")
outnames <-  str_replace_all( outnames, "A Lady from ", "")
outnames <-  str_replace_all( outnames, "Aishling Campbell from ", "")
outnames <-  str_replace_all( outnames, "A C Bryan from ", "")
outnames <-  str_replace_all( outnames, " Ed Peate", "Ed Peate")
outnames <-  str_replace_all( outnames, " Mrs", "Mrs")
outnames <-  str_replace_all( outnames, "Avalon Bloodstock from ", "")
outnames <-  str_replace_all( outnames, "Brendan Peoples from ", "")
outnames <-  str_replace_all( outnames, "D Harvey from ", "")
outnames <-  str_replace_all( outnames, "Darshams Farm for ", "")
outnames <-  str_replace_all( outnames, "DJP Turner from ", "")
outnames <-  str_replace_all( outnames, "Downfield Cottage Stud from ", "")
outnames <-  str_replace_all( outnames, "Ecuries", "Ecurie")
outnames <-  str_replace_all( outnames, "FDG", "Ecurie F D G")
outnames <-  str_replace_all( outnames, "Mark Vickers from ", "")
outnames <-  str_replace_all( outnames, "Moyns Park Estate  Stud from ", "")
outnames <-  str_replace_all( outnames, "Mrs J K M Oliver from ", "")
outnames <-  str_replace_all( outnames, "Mrs J Penman from ", "")
outnames <-  str_replace_all( outnames, "Muhammad Noman from ", "")
outnames <-  str_replace_all( outnames, "N Hardy Transport from ", "")
outnames <-  str_replace_all( outnames, "P  W Byrne from ", "")
outnames <-  str_replace_all( outnames, "P Newton from ", "")
outnames <-  str_replace_all( outnames, "Padraig Pierce fromBallyhampshire", "Ballyhampshire")
outnames <-  str_replace_all( outnames, "Pat Cloke fromBallybrennan", "Ballybrennan")
outnames <-  str_replace_all( outnames, "Prime Of Life 3 from ", "")
outnames <-  str_replace_all( outnames, " from Ed Dunlop Racing Stables", "")
outnames <-  str_replace_all( outnames, "Rathbarry Stud fromThe", "The")
outnames <-  str_replace_all( outnames, "RJ  R Marley fromChurch", "Church")
outnames <-  str_replace_all( outnames, "Stud A Dispersal", "Stud")
outnames <-  str_replace_all( outnames, "Sonna Demense Stud", "Sonna Demesne Stud")
outnames <-  str_replace_all( outnames, "T Pearson from ", "")
outnames <-  str_replace_all( outnames, "The Channel Consignment fromJamie", "Jamie")
outnames <-  str_replace_all( outnames, "Tim Pearson from ", "")
outnames <-  str_replace_all( outnames, "Tom Shanahan from ", "")
outnames <-  str_replace_all( outnames, "Tony  Mary McKiernan from ", "")
outnames <-  str_replace_all( outnames, "Consigned by ", "")
outnames <-  str_replace_all( outnames, "Sherborne", "Sherbourne")
outnames <-  str_replace_all( outnames, "Greenhills Farm", "Katie Walsh")
outnames <-  str_replace_all( outnames, "Walsh Katie", "Katie Walsh")
outnames <-  str_replace_all( outnames, "Katie Walsh ", "Katie Walsh")
outnames <-  str_replace_all( outnames, "Johnstown", "Johnstown Stud")
outnames <-  str_replace_all( outnames, "Johnstown Stud Stud", "Johnstown Stud")
outnames <-  str_replace_all( outnames, "Rockview Stud", "Rockview Stables")
outnames <-  str_replace_all( outnames, "JerpointChurch", "Church")
outnames <-  str_replace_all( outnames, "Lewinstown Stables", "Lewinstown")
outnames <-  str_replace_all( outnames, "Manor Farm Stud", "Manor Farm")
outnames <-  str_replace_all( outnames, "Stud Stud ", "Stud")
outnames <-  str_replace_all( outnames, "Stud ", "Stud")
outnames <-  str_replace_all( outnames, "House ", "House")
outnames <-  str_replace_all( outnames, "HouseStud", "House Stud")
outnames <-  str_replace_all( outnames, "HouseStables", "House Stables")
outnames <-  str_replace_all( outnames, "StudStud", "Stud")
outnames <-  str_replace_all( outnames, "Sonna Demesne Stables", "Sonna Demense Stud")
outnames <-  str_replace_all( outnames, "StudStables", "Stud Stables")
outnames <-  str_replace_all( outnames, "Ballinahalla", "Ballinahulla")
outnames <-  str_replace_all( outnames, "Wind Mill", "Windmill")
outnames <-  str_replace_all( outnames, "Demense", "Demesne")
outnames <-  str_replace_all( outnames, "Demesne Stables", "Demesne Stud")
outnames <-  str_replace_all( outnames, "StudFarm", "Stud Farm")
outnames <-  str_replace_all( outnames, "Freigh", "Feigh")
outnames <-  str_replace_all( outnames, "Crolane House", "Crohane House")
outnames <-  str_replace_all( outnames, "Crohane Stud", "Crohane House")
outnames <-  str_replace_all( outnames, "Clenagh Castle Stud Stables", "Clenagh Castle Stud")
outnames <-  str_replace_all( outnames, "Bushypark", "Bushy Park")
outnames <-  str_replace_all( outnames, "Corrig View Stables", "Corrig View")
outnames <-  str_replace_all( outnames, "Corrig View", "Corrig View Stables")
outnames <-  str_replace_all( outnames, "Knockgraffon Stables", "Knockgraffon")
outnames <-  str_replace_all( outnames, "Knockgraffon", "Knockgraffon Stables")
outnames <-  str_replace_all( outnames, "Tinvaun Stables", "Tinvaun Stud")
outnames <-  str_replace_all( outnames, " Co Meath", "")
outnames <-  str_replace_all( outnames, "Killaminoge", "Killaminogue")
outnames <-  str_replace_all( outnames, "Saubouas ", "Saubouas")
outnames <-  str_replace_all( outnames, "Mt Leinster", "Mount Leinster")
outnames <-  str_replace_all( outnames, "Leblanc ", "Leblanc")
outnames <-  str_replace_all( outnames, "Stables, Ireland", "Stables")
outnames <-  str_replace_all( outnames, "C\\ A\\ J Stables", "CAJ Stables")
outnames <-  str_replace_all( outnames, "Athnid Stud", "Athnid Stables")
#
##########
# 29-Mar-17 new additions from DBS catalogue
outnames <-  str_replace_all( outnames, "Church Farm Stables  Horse Park Stud", "Horse Park Stud")
outnames <-  str_replace_all( outnames, "Browne John", "Mocklershill")

#outnames <-  str_replace_all( outnames, "FEP Ltd.", "FEP Ltd")

# get rid of Froms here , in yearling sale names
a <- str_locate(outnames, " from")[,1] + 5
outnames2 <- str_trim(substr( outnames, a, 1000))

z <- which( !is.na(a))
outnames[z] <- outnames2[z]

# back to the parsing
outnames <- str_replace( outnames, "Studfrom", "Stud from")
outnames <- str_replace( outnames, "Housefrom", "House from")
outnames <- str_replace( outnames, "Stablesfrom", "Stable from")
outnames <- str_replace( outnames, "HouseFarm", "House Farm")
outnames <- str_replace( outnames, "HouseThoroughbreds", "House")
outnames <- str_replace( outnames, "Studfrom", "Stud from")
outnames <- str_replace( outnames, "Studand", "Stud")

outnames <- str_replace( outnames, "Hse", "House")
outnames <- str_replace( outnames, "Overbury Stallions", "Overbury Stud")
outnames <- str_trim(str_replace( outnames, "To dissolve", ""))
outnames <- str_trim(str_replace( outnames, "To Dissolve", ""))
outnames <- str_trim(str_replace( outnames, "to Dissolve", ""))
outnames <- str_trim(str_replace( outnames, "StudKilkenny", "Stud"))
outnames <- str_trim(str_replace( outnames, "StudNewmarket", "Stud"))
outnames <- str_trim(str_replace( outnames, "Studs", "Stud"))
outnames <- str_trim(str_replace( outnames, "Hascombe  Valiant", "Hascombe"))
outnames <- str_trim(str_replace( outnames, "Srud", "Stud"))
outnames <- str_trim(str_replace( outnames, "StudCo Laois", "Stud"))
outnames <- str_trim(str_replace( outnames, "StudMiddleham", "Stud"))
outnames <- str_trim(str_replace( outnames, "StudSales Division", "Stud"))
outnames <- str_trim(str_replace( outnames, "Mountainview Stud", " Mountain View Stud"))
outnames <- str_trim(str_replace( outnames, "Co Kildare", ""))
outnames <- str_trim(str_replace( outnames, "Kildare", ""))
outnames <- str_trim(str_replace( outnames, "Co Limerick", ""))
outnames <- str_trim(str_replace( outnames, "Limerick", ""))
outnames <- str_trim(str_replace( outnames, "Farm  Stud", "Farm Stud"))
outnames <- str_trim(str_replace( outnames, "Miltown", "Milltown"))
outnames <- str_trim(str_replace( outnames, "Manor Stud", "Manor"))
outnames <- str_trim(str_replace( outnames, " Ardoon", ""))
outnames <- str_trim(str_replace( outnames, "Fields Stud", "Field Stud"))
outnames <- str_trim(str_replace( outnames, "StudfromFurnace", "Stud from Furnace"))
outnames <- str_trim(str_replace( outnames, " Bickmarsh", "Bickmarsh"))

outnames <- str_trim(str_replace( outnames,"Ballinahulla Stable fromBallinahulla Stables", "Ballinahulla Stables"))
outnames <- str_trim(str_replace( outnames,"Baroda  Colbinstown Stud" ,  "Colbinstown Stud"))
outnames <- str_trim(str_replace( outnames,"Malcolm Bastard", "Bastard"))
outnames <- str_trim(str_replace( outnames,"Bastard", "Malcolm Bastard"))
outnames <- str_trim(str_replace( outnames,"Bloomsbury Stud from Machell Place StablesE Vaughan","Bloomsbury Stud"))
outnames <- str_trim(str_replace( outnames, "Emma OGorman", "Seven Springs Stables"))
outnames <- str_trim(str_replace( outnames,"E OGorman" ,  "Seven Springs Stables"))
outnames <- str_trim(str_replace( outnames,"Katie Walshfrom Bushy Park Stables", "Katie Walsh"))
outnames <- str_trim(str_replace( outnames,"Killala House Stable from Derryconnor Stud", "Killala House"))  
outnames <- str_trim(str_replace( outnames,"Lynn Lodge StudCo Westmeath", "Lynn Lodge Stud"))
outnames <- str_trim(str_replace( outnames,"Maunby House StablesD Barron", "Maunby House Stables"))
outnames <- str_trim(str_replace( outnames,"Musley Bank StablesR Fahey", "Musley Bank Stables"))
 
outnames <- str_trim(str_replace( outnames,"Walton Field Stud from Walton Fields Stud" , "Walton Field Stud"))
outnames <- str_trim(str_replace( outnames,"Woodhall Stud from Woodhall Stud", "Wood Hall Stud"))

outnames <- str_trim(str_replace( outnames, "The Jamie Railton" , "Jamie Railton"))
outnames <- str_trim(str_replace( outnames, "Jamie Railton", "Jamie Railton - Channel")) 
outnames <- str_trim(str_replace( outnames, "CHANNEL CONSIGNMENT", "Jamie Railton - Channel")) 
outnames <- str_trim(str_replace( outnames, "Ecurie F D G", "Ecurie du Grand Ferron"))
outnames <- str_trim(str_replace( outnames, "Ecurie PrevostBaratte", "PrevostBaratte"))
outnames <- str_trim(str_replace( outnames, "NGS", "Norton Grove Stud"))
outnames <- str_trim(str_replace( outnames, "Haras de Saint Arnoult", "Saint Arnoult"))
outnames <- str_trim(str_replace( outnames, "SaintArnoult" , "Saint Arnoult"))
outnames <- str_trim(str_replace( outnames, "Haras du Saubouas", "Saubouas"))                                  
outnames <- str_trim(str_replace( outnames, "Lackendarra StablesE Linehan", "Lackendarra Stables"))
outnames <- str_trim(str_replace( outnames, "Manor House StablesLLP T Dascombe", "Manor House Stud"))
outnames <- str_trim(str_replace( outnames, "Manor Farm Stables", "Manor Farm"))
outnames <- str_trim(str_replace( outnames, "Mm Racing" , "mm Racing"))
outnames <- str_trim(str_replace( outnames, "Mam Racing" , "mm Racing"))
#outnames <- str_trim(str_replace( outnames, "Terrys Wood Farm", "Terry\\´s Wood Farm"))
outnames <- str_trim(str_replace( outnames, "The ", ""))
outnames <- str_trim(str_replace( outnames, "Beckhampton House Stables", "Beckhampton Stables"))


#outnames <- str_trim(str_replace( outnames, "Morna McDowall", "Grove Stud"))
#outnames <- str_trim(str_replace( outnames, "McDowall Morna", "Grove Stud"))
#outnames <- str_trim(str_replace( outnames, "McDowall", "Grove Stud"))

outnames <- str_trim(str_replace( outnames, "Morna", ""))
outnames <- str_trim(str_replace( outnames, "McDowall", "Morna McDowall"))


outnames <-  str_replace( outnames, "Jamie Railton - ChannelThe", "Jamie Railton - Channel")
outnames <-  str_replace( outnames, "RailtonJamie", "Jamie Railton - Channel")
outnames <-  str_replace( outnames, "Jamie Jamie ", "Jamie ")
outnames <-  str_replace( outnames, "ChannelJamie", "Channel")



outnames <- str_trim(str_replace( outnames, "Malcolm Bastard M" , "Malcolm Bastard"))
outnames <- str_trim(str_replace( outnames, "mm racing", "mm Racing"))
outnames <- str_trim(str_replace( outnames, "Mocklershill  Haras des Capucines", "Mocklershill"))

outnames <- str_trim(str_replace( outnames, "Murphy Stan", "Murphy"))
outnames <- str_trim(str_replace( outnames, "Murphy", "Stan Murphy"))
outnames <- str_trim(str_replace( outnames, "Stan Stan ", "Stan "))


outnames <- str_trim(str_replace( outnames, "Mount Corbitt StablesJ Culloty", "Mount Corbitt Stables"))

#outnames <- str_trim(str_replace( outnames, "Walsh W J", "Walsh"))
#outnames <- str_trim(str_replace( outnames, "Walsh", "WJ Walsh"))

outnames <- str_trim(str_replace( outnames, "Barrate", "Baratte"))
outnames <- str_trim(str_replace( outnames, "Furze Stables", "Furze Stable"))
outnames <- str_trim(str_replace( outnames, "Mosslodge", "Moss Lodge"))
outnames <- str_trim(str_replace( outnames, "Ballyculen", "Ballycullen"))
outnames <- str_trim(str_replace( outnames, "Ballyvourgal", "Ballyvorgal"))

outnames <-  str_replace_all( outnames, "Ballinahulla", "Ballinahulla Stables")
outnames <-  str_replace_all( outnames, "Ballinahulla Stables Stables", "Ballinahulla Stables")
#
# trim here
outnames <- str_trim( outnames)
#
##########
# 19-Mar-18 more tidyups
#
outnames <- str_trim(str_replace( outnames," fromBallinahulla Stables", ""))
outnames <-  str_replace_all( outnames, "Ballinahulla", "Ballinahulla Stables")
outnames <-  str_replace_all( outnames, "Ballinahulla Stables Stables", "Ballinahulla Stables")
outnames <-  str_replace_all( outnames, "Ballyvorgal Stables", "Ballyvourgal Stables")
outnames <-  str_replace_all( outnames, "Baroda  Colbinstown Stud", "Baroda and Colbinstown Stud")
outnames <-  str_replace_all( outnames, "C A J Stables", "CAJ Stables")
outnames <-  str_replace_all( outnames, "Carrick O\\´Brien Stables", "Carrick OBrien Stables")
outnames <-  str_replace_all( outnames, "French Furs Road Stud", "French Furze")
outnames <-  str_replace_all( outnames, "GanseraLeveque Equine", "GanseraLeveque")
outnames <-  str_replace_all( outnames, "GanseraLeveque", "Gansera Leveque")
outnames <-  str_replace_all( outnames, "Hardwood Farm", "Hardwood Stud")
outnames <-  str_replace_all( outnames, "Hawthorn Stables", "Hawthorn Villa Stud")
outnames <-  str_replace_all( outnames, "Laurel Stud", "Laurel Park")
outnames <-  str_replace_all( outnames, "Laurel Park Stables", "Laurel Park")
outnames <-  str_replace_all( outnames, "Lewinstown Farm", "Lewinstown")
outnames <-  str_replace_all( outnames, "Lewinstown", "Lewinstown Farm")
outnames <-  str_replace_all( outnames, "Manor House StablesLLP", "Manor House Stud")
outnames <-  str_replace_all( outnames, "McDowall Morna", "Grove Stud")
outnames <-  str_replace_all( outnames, "Milestream Stud", "Milestream Stables")
outnames <-  str_replace_all( outnames, "Mocklershill Stud", "Mocklershill")
outnames <-  str_replace_all( outnames, "SaintArnoult", "Saint Arnoult")
outnames <-  str_replace_all( outnames, "The ", "")
outnames <-  str_replace_all( outnames, "Woodhall Stud from Woodhall Stud", "Woodhall Stud")
outnames <-  str_replace_all( outnames, "mm racing", "mm Racing")
#outnames <-  str_replace_all( outnames, "", "")
#outnames <-  str_replace_all( outnames, "", "")
#outnames <-  str_replace_all( outnames, "", "")
#outnames <-  str_replace_all( outnames, "", "")
#outnames <-  str_replace_all( outnames, "", "")
#outnames <-  str_replace_all( outnames, "", "")
#outnames <-  str_replace_all( outnames, "", "")




return(outnames)

}
# end of function
